### ISSUE TITLE
[Tracking] Kestrel config asks

### ISSUE THREAD

**Issue by anurse** [microsoft/reverse-proxy#10]
Here are things we expect to need expanded on for kestrel's existing config system:

- [x] Endpoint config reload: https://github.com/dotnet/aspnetcore/issues/19376
- [x] Backpressure: https://github.com/dotnet/aspnetcore/issues/13295
  - Planned for 6.0
- [x] [EPIC] HTTPS and Certificate Handling in Kestrel: https://github.com/dotnet/aspnetcore/issues/21512
  - [x] SNI config: https://github.com/dotnet/aspnetcore/issues/15144 (Working)
    - Tracked individually by https://github.com/microsoft/reverse-proxy/issues/86
    - In 5.0.0-preview8 milestone
  - [x] Client cert mode: https://github.com/dotnet/aspnetcore/issues/18660
  - [x] PEM certs: https://github.com/dotnet/aspnetcore/issues/4706
    - PR open by @javiercn: https://github.com/dotnet/aspnetcore/pull/23584

**Comment by karelz** [comment]
Triage: All covered.
