### ISSUE TITLE
Changes dependant on targetting 6.0

### ISSUE THREAD

**Issue by MihaZupan** [microsoft/reverse-proxy#1055]
List of known changes we should do in Yarp once adding a 6.0 target (and/or more convenient after dropping 3.1):
- [ ] Use non-validated header enumeration https://github.com/dotnet/runtime/issues/35126#issuecomment-854040319
- [ ] Call Cancellable/Sync overloads of `HttpContent.ReadAsStream*` #770 
- [ ] Doc https://github.com/dotnet/aspnetcore/pull/33776 here: https://github.com/microsoft/reverse-proxy/blob/16ab855a5be980a0cf5fd21e9a7028190b6e7dda/docs/docfx/articles/http-client-config.md#httpclient
- [x] `CancellationTokenSource` pooling #902
- [x] Remove `ActivityPropagationHandler` in favour of the [`DistributedContextPropagator`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.distributedcontextpropagator) that can be customized on a per-handler basis https://github.com/dotnet/runtime/issues/55556
- [x] Use [Random.Shared](https://github.com/dotnet/runtime/issues/43887) in `RandomFactory`
- [x] Update `NameResolutionMetrics` to include `current-dns-lookups` https://github.com/dotnet/runtime/pull/49146
- [X] Implement the cancellable overload of HttpContent.SerializeToStreamAsync (5.0) (#1271)
- [x] Use [`WaitAsync`](https://github.com/dotnet/runtime/blob/v6.0.0-preview.7.21377.19/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs#L15) task timeout extensions instead of `TimeoutAfter`

Feel free to add anything I may be missing

**Comment by Kahbazi** [comment]
How about using [Random.Shared](https://github.com/dotnet/runtime/issues/43887) in `RandomFactory`?

**Comment by Tratcher** [comment]
Note adding 6.0 support is independent from dropping 3.1 support. Are there any of these you think are prohibitive to #if light-up on 5.0 or 6.0 while still supporting 3.1?

**Comment by MihaZupan** [comment]
For #770 we should just wait to drop 3.1. For others it's actually that we need 6.0.

**Comment by davidfowl** [comment]
Just move the ifdefs to extension methods that noop, it'll keep the code clean. It's the technique we use in Pipelines and Channels in the BCL.

- https://github.com/dotnet/runtime/blob/41af30ca291e0435083c0d4b5d70e2939e0dbc3d/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/StreamExtensions.netstandard.cs
- https://github.com/dotnet/runtime/blob/41af30ca291e0435083c0d4b5d70e2939e0dbc3d/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/CancellationTokenExtensions.netstandard.cs

You could do the same with TryReset and assume it always returns false.

**Comment by Tratcher** [comment]
- [ ] Implement the cancellable overload of HttpContent.SerializeToStreamAsync
https://github.com/dotnet/runtime/blob/c14ac488cc5f7d2ad71e7f81d6a05a1da8c76237/src/libraries/System.Net.Http/src/System/Net/Http/HttpContent.cs#L354
https://github.com/microsoft/reverse-proxy/blob/d593701b5839ddd8d2422c2044d1e0ada74f2b18/src/ReverseProxy/Proxy/StreamCopyHttpContent.cs#L119

**Comment by Tratcher** [comment]
- [ ] Doc https://github.com/dotnet/aspnetcore/pull/33776 here: https://github.com/microsoft/reverse-proxy/blob/16ab855a5be980a0cf5fd21e9a7028190b6e7dda/docs/docfx/articles/http-client-config.md#httpclient

**Comment by Kahbazi** [comment]
Use [LoggerMessageAttribute](https://github.com/dotnet/runtime/blob/25bb59daa0b984640bd4e1620f11b279cb0c4b02/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/LoggerMessageAttribute.cs#L32).

**Comment by Kahbazi** [comment]
Use [PeriodicTimer](https://github.com/dotnet/runtime/blob/a3b83b91920c88041649ec229cbc9ece446cd5a6/src/libraries/System.Private.CoreLib/src/System/Threading/PeriodicTimer.cs#L17).

**Comment by WeihanLi** [comment]
Use [`WaitAsync`](https://github.com/dotnet/runtime/blob/v6.0.0-preview.7.21377.19/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs#L15) task timeout extensions instead of `TimeoutAfter`

**Comment by MihaZupan** [comment]
We are only using this within `EntityActionScheduler` where the API surface is different from what `PeriodicTimer` offers.

**Comment by Kahbazi** [comment]
> We are only using this within `EntityActionScheduler` where the API surface is different from what `PeriodicTimer` offers.

I assumed the overall performance might be better.

**Comment by MihaZupan** [comment]
Now that we are targeting 6.0 and most items have been completed, I moved the remaining ones into separate issues (#1346 #1347)
