### ISSUE TITLE
Preview 12 release checklist

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#1120]
See [Release.md](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Release.md) for detailed instructions.

- [x] Ensure there's a release branch created (see [Branching](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Branching.md))
- [x] Ensure the `Version.props` has the `PreReleaseVersionLabel` updated to the next preview
- [x] Identify and validate the build on the `microsoft-reverse-proxy-official` pipeline
- [x] Release the build
- [x] Tag the commit
- [x] Draft release notes
- [x] Update samples to use updated package versions
- [x] Publish the docs
- [x] Publish release notes
- [ ] Close the [old milestone](https://github.com/microsoft/reverse-proxy/milestones)
- [ ] Announce on social media
- [ ] Set the preview branch to protected
- [ ] Delete the [previous preview branch](https://github.com/microsoft/reverse-proxy/branches)
