### ISSUE TITLE
Preview 12.21451.3 release checklist

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#1224]
See [Release.md](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Release.md) for detailed instructions.

- [x] Ensure there's a release branch created (see [Branching](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Branching.md))
- [x] Ensure the `Version.props` has the `PreReleaseVersionLabel` updated to the next preview
- [x] Identify and validate the build on the `microsoft-reverse-proxy-official` pipeline
  - https://dev.azure.com/dnceng/internal/_build/results?buildId=1334535
- [x] Release the build https://www.nuget.org/packages/Yarp.ReverseProxy/1.0.0-preview.12.21451.3
- [x] Tag the commit https://github.com/microsoft/reverse-proxy/tree/v1.0.0-preview12.21451.3
- [x] Draft release notes
- [x] Update samples to use updated package versions
- [ ] Publish the docs
- [x] Publish release notes https://github.com/microsoft/reverse-proxy/releases/tag/v1.0.0-preview12.21451.3
- [x] Close the [old milestone](https://github.com/microsoft/reverse-proxy/milestones)
- [x] Announce on social media https://twitter.com/Tratcher/status/1433138943239745539
- [x] Set the preview branch to protected
- [x] Delete the [previous preview branch](https://github.com/microsoft/reverse-proxy/branches)
- [ ] Request source code archival

**Comment by Tratcher** [comment]
> Update samples to use updated package versions

The new nuget package isn't on the right feed for this? @alnikola how did you update them last time?

**Comment by Tratcher** [comment]
It looks like our preview branches weren't set up to publish to our feed. I think I've fixed that in darc.

**Comment by alnikola** [comment]
Sorry, I didn't get the issue completely. If you still need help, could you please clarify a bit more?
