### ISSUE TITLE
Rc1 release checklist

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#1310]
See [Release.md](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Release.md) for detailed instructions.

- [x] Ensure there's a release branch created (see [Branching](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Branching.md)) https://github.com/microsoft/reverse-proxy/tree/release/1.0.0-rc.1
- [x] Ensure the `Version.props` has the `PreReleaseVersionLabel` updated to the next preview https://github.com/microsoft/reverse-proxy/pull/1313
- [x] Identify and validate the build on the `microsoft-reverse-proxy-official` pipeline
  - https://dev.azure.com/dnceng/internal/_build/results?buildId=1432651&view=results
  - Yarp.ReverseProxy.1.0.0-rc.1.21520.4.nupkg
  - 822070029a9105d1df940c78ae34d6e3e83e4cbc
- [x] Release the build
- [x] Tag the commit https://github.com/microsoft/reverse-proxy/tree/v1.0.0-rc.1
- [x] Draft release notes
- [x] Update samples to use updated package versions
- [x] Publish the docs
- [x] Publish release notes
- [x] Close the [old milestone](https://github.com/microsoft/reverse-proxy/milestones)
- [x] Announce on social media https://twitter.com/Tratcher/status/1451245236856836096
- [x] Set the preview branch to protected
- [x] Delete the [previous preview branch](https://github.com/microsoft/reverse-proxy/branches)
- [x] Request source code archival

**Comment by Tratcher** [comment]
Followups:
 - [ ] Remove this line about updating pools: https://github.com/microsoft/reverse-proxy/blame/main/docs/operations/Branching.md#L7
