### ISSUE TITLE
1.0 release checklist

### ISSUE THREAD

**Issue by MihaZupan** [microsoft/reverse-proxy#1353]
See [Release.md](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Release.md) for detailed instructions.

- [x] Ensure there's a release branch created (see [Branching](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Branching.md))
  - https://github.com/microsoft/reverse-proxy/tree/release/1.0
  - Branched on 08f6dd95bf1a940959a41f4c4a5364f7c5486060
- [x] Ensure the `Version.props` has the `PreReleaseVersionLabel` updated to the next preview
  - #1358
- [x] Identify and validate the build on the `microsoft-reverse-proxy-official` pipeline
  - https://dev.azure.com/dnceng/internal/_build/results?buildId=1457057
- [x] Release the build (unlisted)
  - https://www.nuget.org/packages/Yarp.ReverseProxy/1.0.0
  - https://www.nuget.org/packages/Yarp.Telemetry.Consumption/1.0.0
- [x] Tag the commit
  - https://github.com/microsoft/reverse-proxy/releases/tag/v1.0.0
- [x] Draft release notes
- [x] relist the packages on nuget
- [x] Update samples to use updated package versions
  - ~~#1362~~ replaced by #1364
- [x] Publish the docs
  - #1364
- [x] Publish release notes
  - https://github.com/microsoft/reverse-proxy/releases/tag/v1.0.0
- [x] Close the [old milestone](https://github.com/microsoft/reverse-proxy/milestones)
- [x] Announce on social media
  - https://twitter.com/_MihaZupan/status/1458110656650035201
- [x] Set the preview branch to protected
- [x] Delete the [previous preview branch](https://github.com/microsoft/reverse-proxy/branches)
- [x] Request source code archival
- [ ] Update docs (for changes like #1359)

**Comment by WeihanLi** [comment]
The [roadmap](https://github.com/microsoft/reverse-proxy/blob/main/docs/roadmap.md) should be updated also

**Comment by karelz** [comment]
@WeihanLi good point, it is now tackled in PR #1374
