### ISSUE TITLE
1.1.0 release checklist

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#1676]
See [Release.md](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Release.md) for detailed instructions.

- [x] Ensure there's a release branch created (see [Branching](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Branching.md))
- [x] Ensure the `Version.props` has the `PreReleaseVersionLabel` updated to the next preview
- [x] Identify and validate the build on the `microsoft-reverse-proxy-official` pipeline
  - https://dev.azure.com/dnceng/internal/_build/results?buildId=1745020&view=artifacts&pathAsName=false&type=publishedArtifacts
- [x] Release the build https://www.nuget.org/packages/Yarp.ReverseProxy/1.1.0
- [x] Tag the commit
- [x] Draft release notes
- [x] Update samples to use updated package versions
- [x] Publish the docs
- [x] Publish release notes
- [x] Close the [old milestone](https://github.com/microsoft/reverse-proxy/milestones)
- [x] Announce on social media
- [x] Set the preview branch to protected
- [x] Delete the [previous preview branch](https://github.com/microsoft/reverse-proxy/branches)
- [x] Request source code archival
