### ISSUE TITLE
1.1.1 release checklist

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#1785]
See [Release.md](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Release.md) for detailed instructions.

- [x] Update the versions for rtw
- [ ] ~~Ensure the `Version.props` has the `PreReleaseVersionLabel` updated to the next preview~~
- [x] Identify and validate the build on the `microsoft-reverse-proxy-official` pipeline
- [x] Release the build
- [x] Tag the commit
- [x] Draft release notes
- [ ] ~~Update samples to use updated package versions~~
- [ ] ~~Publish the docs~~
- [x] Publish release notes
- [ ] ~~Close the [old milestone](https://github.com/microsoft/reverse-proxy/milestones)~~
- [ ] ~~Announce on social media~~
- [ ] ~~Set the preview branch to protected~~
- [ ] ~~Delete the [previous preview branch](https://github.com/microsoft/reverse-proxy/branches)~~
- [ ] ~~Request source code archival~~
- [x] Backport the fix to main
