### ISSUE TITLE
2.0 GA release checklist

### ISSUE THREAD

**Issue by adityamandaleeka** [microsoft/reverse-proxy#2011]
See [Release.md](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Release.md) for detailed instructions.

- [ ] Ensure there's a release branch created (see [Branching](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Branching.md))
- [ ] Ensure the `Version.props` has the `PreReleaseVersionLabel` updated to the next preview
- [ ] Identify and validate the build on the `microsoft-reverse-proxy-official` pipeline
- [ ] Release the build
- [ ] Tag the commit
- [ ] Draft release notes
- [ ] Update samples to use updated package versions
- [ ] Publish the docs
- [ ] Publish release notes
- [ ] Close the [old milestone](https://github.com/microsoft/reverse-proxy/milestones)
- [ ] Announce on social media
- [ ] Set the preview branch to protected
- [ ] Delete the [previous preview branch](https://github.com/microsoft/reverse-proxy/branches)
- [ ] Request source code archival

**Comment by adityamandaleeka** [comment]
We are aiming to have this released around February 20.
