### ISSUE TITLE
2.1 Preview 1 release checklist

### ISSUE THREAD

**Issue by adityamandaleeka** [microsoft/reverse-proxy#2305]
See [Release.md](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Release.md) for detailed instructions.

- [x] Ensure there's a release branch created (see [Branching](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Branching.md))
- [x] Ensure the `Version.props` has the `PreReleaseVersionLabel` updated to the next preview
- [x] Identify and validate the build on the `microsoft-reverse-proxy-official` pipeline
- [x] Release the build
- [x] Tag the commit - v2.1.0-preview.1
- [x] Draft release notes
- [ ] ~Update samples to use updated package versions~
- [ ] ~Publish the docs~
- [x] Publish release notes
- [ ] ~Close the [old milestone](https://github.com/microsoft/reverse-proxy/milestones)~
- [ ] ~Announce on social media~
- [ ] ~Set the preview branch to protected~
- [ ] ~Delete the [previous preview branch](https://github.com/microsoft/reverse-proxy/branches)~
- [ ] Request source code archival

**Comment by Tratcher** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=2308692&view=results
2.1.0-preview.1.23556.5

**Comment by adityamandaleeka** [comment]
Crossing off a bunch of the items since they're covered in https://github.com/microsoft/reverse-proxy/issues/2304, which tracks the real 2.1 release that's happening next week.

**Comment by samsp-msft** [comment]
LGTM
