### ISSUE TITLE
2.2.0 Preview 1 release checklist

### ISSUE THREAD

**Issue by MihaZupan** [microsoft/reverse-proxy#2499]
See [Release.md](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Release.md) for detailed instructions.

- [x] Ensure there's a release branch created (see [Branching](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Branching.md))
  - https://github.com/microsoft/reverse-proxy/tree/release/2.2.0-preview1
- [x] Ensure the `Version.props` has the `PreReleaseVersionLabel` updated to the next preview
  - #2505
- [x] Identify and validate the build on the `microsoft-reverse-proxy-official` pipeline
  - https://github.com/microsoft/reverse-proxy/commit/76e28e25eaff9e4150b185e3320ae614d3a99382
  - https://dev.azure.com/dnceng/internal/_build/results?buildId=2452792
  - `Yarp.ReverseProxy.2.2.0-preview.1.24266.1`
- [x] Release the build
  - https://www.nuget.org/packages/Yarp.ReverseProxy/2.2.0-preview.1.24266.1
  - https://www.nuget.org/packages/Yarp.Telemetry.Consumption/2.2.0-preview.1.24266.1
- [x] Tag the commit
  - https://github.com/microsoft/reverse-proxy/releases/tag/v2.2.0-preview1
- [x] Draft release notes
- [x] Update samples to use updated package versions
  - https://github.com/microsoft/reverse-proxy/commit/80fe92bc58e195f6ca27399a084ab78715e2eb8b
- [x] Publish the docs
- [x] Publish release notes
- [x] Close the [old milestone](https://github.com/microsoft/reverse-proxy/milestones)
- [x] Announce on social media
- [x] Set the preview branch to protected
- [X] ~~Delete the [previous preview branch](https://github.com/microsoft/reverse-proxy/branches)~~
- [x] Request source code archival
