### ISSUE TITLE
2.2 release checklist

### ISSUE THREAD

**Issue by MihaZupan** [microsoft/reverse-proxy#2588]
See [Release.md](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Release.md) for detailed instructions.

- [x] Ensure there's a release branch created (see [Branching](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Branching.md))
  - https://github.com/microsoft/reverse-proxy/tree/release/2.2
- [x] Ensure the `Version.props` has the `PreReleaseVersionLabel` updated to the next preview
  - https://github.com/microsoft/reverse-proxy/pull/2589
- [x] Identify and validate the build on the `microsoft-reverse-proxy-official` pipeline
  - https://dev.azure.com/dnceng/internal/_build/results?buildId=2526988
  - https://github.com/microsoft/reverse-proxy/commit/2a2ebeaedf5f022442ca7fd16beda61d6264544a
- [x] Release the build
  - https://www.nuget.org/packages/Yarp.ReverseProxy/2.2.0
  - https://www.nuget.org/packages/Yarp.Telemetry.Consumption/2.2.0
- [x] Tag the commit
  - https://github.com/microsoft/reverse-proxy/releases/tag/v2.2.0
- [x] Draft release notes
- [x] Update samples to use updated package versions
- [x] Publish the docs
- [x] Publish release notes
- [x] Close the [old milestone](https://github.com/microsoft/reverse-proxy/milestones)
- [ ] Announce on social media
- [x] Set the preview branch to protected
- [x] Delete the [previous preview branch](https://github.com/microsoft/reverse-proxy/branches)
- [x] Request source code archival
