### ISSUE TITLE
Release Preview 4

### ISSUE THREAD

**Issue by karelz** [microsoft/reverse-proxy#374]
- [x] Identify the candidate build: Microsoft.ReverseProxy.1.0.0-preview.4.20424.2
  - https://dev.azure.com/dnceng/internal/_build/results?buildId=785704&view=results
- [x] Create the preview branch at the matching commit
- [x] Set up versioned docs using the preview branch #344
- [x] Verify the build
  - [x] Package metadata and contents
  - [x] Getting started instructions (update in preview branch) #379
  - [x] New preview features
- [x] Stage package for release https://dev.azure.com/dnceng/internal/_releaseProgress?_a=release-pipeline-progress&releaseId=37513
- [x] Create git tag https://github.com/microsoft/reverse-proxy/releases/tag/v1.0.0-preview4
- [x] Draft release notes https://github.com/microsoft/reverse-proxy/releases
  - https://github.com/microsoft/reverse-proxy/releases/tag/untagged-0610b2adb80cd58924c5
- [x] Release package https://www.nuget.org/packages/Microsoft.ReverseProxy/1.0.0-preview.4.20424.2
- [x] Retarget the release docs branch
- [x] Publish release notes
- [x] Close the old milestone
- [x] Delete the old release branch
- [x] Announce on social media https://github.com/microsoft/reverse-proxy/releases/tag/v1.0.0-preview4
- [x] Update master version #378
- [x] Update darc dependencies to rc1 #381
- [ ] Update SDK #382
- [ ] Merge release/preview4 to master #383
- [x] Write up / update the release steps in our ops docs #380
  - https://github.com/microsoft/reverse-proxy/blob/master/docs/operations/Release.md
  - Update our branching docs to reflect that we haven't been using release branches during a lockdown period.
