### ISSUE TITLE
Epic: Ship an extensible/customizable reverse proxy performant enough for cloud scale workloads

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#480]
As a cloud native infrastructure/service developer, I want a reverse proxy solution that is customizable to my needs and performant enough for cloud scale workloads.

From a YARP perspective, this list represents the functionality we consider to be required for a YARP v1.

This includes the following user stories:

**Configuration**
- [x] Proxy supports static config files, with hot reload for handling changes #9 
  - [ ] ~Proxy configuration is extensible for custom metadata on routes, destinations etc #485~
- [x] Proxy supports dynamic configuration pulling from other sources #8
  - [x] Proxy has Service Fabric integration for dynamic discovery of routes #257
  - [x] Proxy can act as a Kubernetes Ingress Controller #200
- [x] Routes can be fully dynamic and discovered on a per request basis for hyper scale hosting  #46

**Routing & inbound connections**
- [x] Proxy can front multiple sites and route based on SNI/Host #14 
- [x] Proxy should enable routing based on header values #405
- [x] Proxy should have active health checks to confirm the state of destinations #228
- [x] Proxy supports Session Affinity to route subsequent requests to the same host#45 
- [ ] ~Proxy can divert routes to support A/B testing, service rollout etc #126~
- [x] Proxy supports multiple algorithms for load balancing across destinations #58
- [x] Proxy supports authentication / authorization for specific routes #122
- [ ] ~Proxy can deliver static files directly #187~
- [ ] ~Support for Lets Encrypt for TLS termination #110~

**Proxying & outbound connections**
- [x] Incoming request Url can be transformed before passing to destination(s) #207
- [x] Requests and responses headers can be transformed #21 
- [x] Http Methods can be transformed (eg POST to PUT) #445
- [x] Outbound http connections to destinations are configurable #282 
- [x] Proxy adds standard headers related to request forwarding #13
- [ ] ~Proxy can be used in a hosted datacenter environment with limitations such as SNAT #62~
- [x] Proxy can handle gRPC traffic including streaming #118
- [x] Proxy component can be used stand-alone for advanced scenarios #408  

**Diagnostics**
- [x] Proxy supplies metrics for monitoring performance #61
- [x] Proxy supplies logs for with pertinent  info for each stage of the request #660
- [ ] ~Proxy has an API for determining its health #125~

**General**
- [ ] ~Proxy is hardened so it can directly face the internet #16~
  - [ ] ~Proxy monitors its own load/health and throttles connections when required #470~
- [x] Proxy has cloud scale performance, and is benchmarked in the lab #51  
- [ ] Proxy has documentation #484
- [x] Customer can add middleware to customize the proxy functionality such as routing, header manipulation #114
- [x] Support for .NET 3.1 & 5 #159
- [ ] ~Support for back pressure #290~

**Packaging**
- [x] Proxy can be consumed as a library so it can be readily extended and customized #143
- [ ] ~Proxy is supplied as a project template for dotnet new #77~
- [ ] ~Proxy is supplied as a pre-built exe with a configuration file #261~
- [ ] ~Proxy is supplied as a pre-built docker image #247~

**Comment by karelz** [comment]
1.0 shipped!
