### ISSUE TITLE
Preview 9 release checklist

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#747]
- [x] Ensure there's a release branch created (see [Branching](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Branching.md))
- [x] Ensure the `Version.props` has the `PreReleaseVersionLabel` updated to the next preview #749
- [x] Identify and validate the build on the `microsoft-reverse-proxy-official` pipeline
  - https://dev.azure.com/dnceng/internal/_build/results?buildId=997478&view=artifacts&pathAsName=false&type=publishedArtifacts
  - Microsoft.ReverseProxy.1.0.0-preview.9.21116.1
- [x] Release the build
- [x] Tag the commit
- [x] Draft release notes
- [x] Publish the docs
- [x] Publish release notes
- [x] Close the [old milestone](https://github.com/microsoft/reverse-proxy/milestones)
- [x] Announce on social media: https://twitter.com/Tratcher/status/1362103326750347267
- [x] Set the preview branch to protected
- [x] Delete the [previous preview branch](https://github.com/microsoft/reverse-proxy/branches)
