### ISSUE TITLE
Rebranding checklist

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#811]
We plan to re-brand this project to be fully independent. This includes updating the:
- [x] Project and package names Microsoft -> Yarp
   - Yarp.ReverseProxy
   - Yarp.ReverseProxy.ServiceFabric
- [x] Namespaces Microsoft -> Yarp
  -  Yarp.ReverseProxy
- [ ] ~~Some APIs like MapReverseProxy~~ (nevermind)
- [ ] Publish the new packages
- [x] Docs
- [x] Samples: Some samples reference published packages for stability.

Things that are not covered by this issue but will likely change later:
- License
- File copyright headers
- CLA process
- Binary signing
- Security issue reporting process (?)
- Github Org - yarpproxy is reserved
- Repo name

**Comment by samsp-msft** [comment]
We are looking at submitting YARP to the CNCF, as a sandbox project. They use the apache license rather than MIT. So it would be changing to apache if accepted.
