### ISSUE TITLE
Preview 10 release checklist

### ISSUE THREAD

**Issue by MihaZupan** [microsoft/reverse-proxy#844]
- [x] Ensure there's a release branch created (see [Branching](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Branching.md))
- [x] Ensure the `Version.props` has the `PreReleaseVersionLabel` updated to the next preview
- [x] Identify and validate the build on the `microsoft-reverse-proxy-official` pipeline
    - https://dev.azure.com/dnceng/internal/_build/results?buildId=1046791&view=artifacts&pathAsName=false&type=publishedArtifacts
    - Yarp.ReverseProxy.1.0.0-preview.10.21168.2
- [x] Release the build https://www.nuget.org/packages?q=Yarp.ReverseProxy
- [x] Tag the commit
- [x] Draft release notes
- [x] Publish the docs
- [x] Publish release notes
- [x] Close the [old milestone](https://github.com/microsoft/reverse-proxy/milestones)
- [x] Announce on social media: https://twitter.com/_MihaZupan/status/1373029900035231749
- [x] Set the preview branch to protected
- [x] Delete the [previous preview branch](https://github.com/microsoft/reverse-proxy/branches)
