### ISSUE TITLE
Preview 11 release checklist

### ISSUE THREAD

**Issue by MihaZupan** [microsoft/reverse-proxy#940]
- [x] Ensure there's a release branch created (see [Branching](https://github.com/microsoft/reverse-proxy/blob/main/docs/operations/Branching.md))
- [x] Ensure the `Version.props` has the `PreReleaseVersionLabel` updated to the next preview
- [x] Identify and validate the build on the `microsoft-reverse-proxy-official` pipeline
  - https://dev.azure.com/dnceng/internal/_build/results?buildId=1104350&view=results
- [x] Release the build
  - https://www.nuget.org/packages/Yarp.ReverseProxy/1.0.0-preview.11.21223.5
- [x] Tag the commit
- [x] Draft release notes
- [x] Publish the docs
- [x] Publish release notes
- [x] Close the [old milestone](https://github.com/microsoft/reverse-proxy/milestones)
- [x] Announce on social media https://twitter.com/_MihaZupan/status/1385712228465352714
- [x] Set the preview branch to protected
- [x] Delete the [previous preview branch](https://github.com/microsoft/reverse-proxy/branches)

Fix branches:
- [x] Protect `release/1.0.0-preview11` and `release/latest`
- [x] Delete `release/1.0.0-preview10` and `release/docs`

**Comment by Tratcher** [comment]
@samsp-msft is working on an new step for this list here: https://github.com/microsoft/reverse-proxy/pull/938
After "Tag the commit"
- [ ] Reset the `release/latest` branch to match the new preview branch.

This shouldn't require a PR or any new commits, it should be a simple reset forward. We likely don't need to make the branch protected.

**Comment by MihaZupan** [comment]
Does it make sense to have both `release/latest` and `release/docs`? They should both have the same meaning now

**Comment by Tratcher** [comment]
Hmm. In theory release/docs could be incrementally updated between releases, but I guess that wouldn't hurt the samples. @samsp-msft does merging these concepts make sense to you?

**Comment by Tratcher** [comment]
@samsp-msft release/docs also targets the prior release and is only updated between releases if we find a bug in the docs. Doc bug fixes would not impact the samples.

**Comment by samsp-msft** [comment]
ok, but lets make it release/latest as that's more obvious as to what it points at

**Comment by Tratcher** [comment]
That seems workable. We'd have to replace `release/docs` in a few places like:
https://github.com/microsoft/reverse-proxy/blob/f10e1a8e0720ee5f96646f1895faa3abdae6f245/.github/workflows/docfx_build.yml#L5

@MihaZupan can you include that with the release steps?

**Comment by Tratcher** [comment]
@MihaZupan Done.

**Comment by MihaZupan** [comment]
Thanks!
